# Generated by Django 5.1.3 on 2024-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(max_length=255)),
                ('resume_file', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
