# Generated by Django 5.1.3 on 2024-11-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='custom_resume_table',
        ),
    ]
